const { withDangerousMod, withMainApplication } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const copyIfExists = (src, dest) => {
  if (!fs.existsSync(src)) return;
  const destDir = path.dirname(dest);
  if (!fs.existsSync(destDir)) fs.mkdirSync(destDir, { recursive: true });
  fs.copyFileSync(src, dest);
};

const plugin = config => {
  // iOS: copy VisionOCR.swift and VisionOCRBridge.m into ios/ directory
  config = withDangerousMod(config, ['ios', async config => {
    const projectRoot = config.modRequest.projectRoot;
    const srcSwift = path.join(projectRoot, 'native', 'ios', 'VisionOCR.swift');
    const srcBridge = path.join(projectRoot, 'native', 'ios', 'VisionOCRBridge.m');
    const destSwift = path.join(projectRoot, 'ios', 'VisionOCR.swift');
    const destBridge = path.join(projectRoot, 'ios', 'VisionOCRBridge.m');
    try {
      copyIfExists(srcSwift, destSwift);
      copyIfExists(srcBridge, destBridge);
    } catch (e) {
      console.warn('VisionOCR plugin iOS copy failed', e);
    }
    return config;
  }]);

  // Android: copy all kotlin sources from native/android into the app java package
  config = withDangerousMod(config, ['android', async config => {
    const projectRoot = config.modRequest.projectRoot;
    const srcDir = path.join(projectRoot, 'native', 'android');
    const destDir = path.join(projectRoot, 'android', 'app', 'src', 'main', 'java', 'com', 'healthdiary', 'ocr');
    try {
      if (fs.existsSync(srcDir)) {
        if (!fs.existsSync(destDir)) fs.mkdirSync(destDir, { recursive: true });
        const files = fs.readdirSync(srcDir);
        for (const f of files) {
          if (f.endsWith('.kt') || f.endsWith('.java')) {
            copyIfExists(path.join(srcDir, f), path.join(destDir, f));
          }
        }
      }
    } catch (e) {
      console.warn('VisionOCR plugin Android copy failed', e);
    }
    return config;
  }]);

  // Patch android/app/build.gradle to add ML Kit dependency if present
  config = withDangerousMod(config, ['android', async config => {
    try {
      const projectRoot = config.modRequest.projectRoot;
      const buildGradlePath = path.join(projectRoot, 'android', 'app', 'build.gradle');
      if (fs.existsSync(buildGradlePath)) {
        let content = fs.readFileSync(buildGradlePath, 'utf8');
        if (!content.match(/com\.google\.mlkit[: ]text-recognition/)) {
          // Try to safely insert implementation into the dependencies block
          const depBlockMatch = content.match(/dependencies\s*\{[\s\S]*?\n\}/);
          if (depBlockMatch) {
            const depBlock = depBlockMatch[0];
            const newDepBlock = depBlock.replace(/\n\}/, '\n    implementation "com.google.mlkit:text-recognition:16.0.0"\n}');
            content = content.replace(depBlock, newDepBlock);
            fs.writeFileSync(buildGradlePath, content, 'utf8');
          } else {
            // Fallback: append implementation at end
            content += '\ndependencies {\n    implementation "com.google.mlkit:text-recognition:16.0.0"\n}\n';
            fs.writeFileSync(buildGradlePath, content, 'utf8');
          }
        }
      }
    } catch (e) {
      console.warn('VisionOCR plugin patch build.gradle failed', e);
    }
    return config;
  }]);

  // NOTE: we deliberately do NOT declare com.google.mlkit.vision.DEPENDENCIES
  // (which would install the OCR model at install-time instead of lazily on
  // first use) — expo-dev-client's own expo-dev-launcher module already
  // declares that same meta-data key with value "barcode_ui" for its QR-based
  // dev-server connection, and Android's manifest merger fails on two
  // differing values for the same key. Not worth the coupling/fragility to
  // work around for what's purely a first-use latency optimization.

  // Register MLKitOCRPackage in MainApplication.kt — it's not autolinked, and
  // MainApplication.kt is regenerated by every `expo prebuild`, so without
  // this the class-copy step above would go silently unused after the very
  // next prebuild.
  config = withMainApplication(config, config => {
    if (config.modResults.language !== 'kt') {
      console.warn('VisionOCR plugin: MainApplication is not Kotlin, skipping MLKitOCRPackage registration (add it manually)');
      return config;
    }
    const IMPORT_LINE = 'import com.healthdiary.ocr.MLKitOCRPackage';
    const ADD_CALL = 'add(MLKitOCRPackage())';
    let contents = config.modResults.contents;
    if (!contents.includes(IMPORT_LINE)) {
      contents = contents.replace(
        /(import expo\.modules\.ExpoReactHostFactory\n)/,
        `$1\n${IMPORT_LINE}\n`
      );
    }
    if (!contents.includes(ADD_CALL)) {
      contents = contents.replace(
        /(PackageList\(this\)\.packages\.apply \{\n)/,
        `$1          ${ADD_CALL}\n`
      );
    }
    config.modResults.contents = contents;
    return config;
  });

  return config;
};

module.exports = plugin;
